-- CreateTable
CREATE TABLE `t_usuarios` (
    `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
    `nombre_user` VARCHAR(200) NOT NULL,
    `dni_user` VARCHAR(20) NULL,
    `email_user` VARCHAR(255) NOT NULL,
    `telefono_user` VARCHAR(20) NULL,
    `direccion_user` TEXT NULL,
    `foto_url_user` VARCHAR(500) NULL,
    `password_user` VARCHAR(255) NOT NULL,
    `must_change_password` BOOLEAN NULL DEFAULT false,
    `email_verificado` BOOLEAN NULL DEFAULT false,
    `intentos_login_fallidos` INTEGER NULL DEFAULT 0,
    `bloqueado_hasta` TIMESTAMP(0) NULL,
    `ultimo_login` TIMESTAMP(0) NULL,
    `token_recuperacion` VARCHAR(100) NULL,
    `token_expiracion` TIMESTAMP(0) NULL,
    `proveedor_oauth` ENUM('google', 'facebook', 'apple') NULL,
    `sub_oauth` VARCHAR(100) NULL,
    `activo` BOOLEAN NULL DEFAULT true,
    `fecha_creacion` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `fecha_modificacion` DATETIME(0) NULL,
    `ip_registro` VARCHAR(45) NULL,
    `user_agent` VARCHAR(500) NULL,
    `codigo_de_invitacion` VARCHAR(50) NULL,
    `intentos_reenvio_verificacion` INTEGER NULL DEFAULT 0,
    `ultimo_reenvio_verificacion` TIMESTAMP(0) NULL,
    `bloqueado_reenvio_hasta` TIMESTAMP(0) NULL,

    UNIQUE INDEX `t_usuarios_dni_user_key`(`dni_user`),
    UNIQUE INDEX `t_usuarios_email_user_key`(`email_user`),
    UNIQUE INDEX `t_usuarios_sub_oauth_key`(`sub_oauth`),
    INDEX `idx_email_user`(`email_user`),
    INDEX `idx_dni_user`(`dni_user`),
    INDEX `idx_ultimo_login`(`ultimo_login`),
    INDEX `idx_fecha_creacion`(`fecha_creacion`),
    INDEX `idx_activo_email`(`activo`, `email_user`),
    INDEX `idx_sub_oauth`(`sub_oauth`),
    INDEX `idx_codigo_invitacion`(`codigo_de_invitacion`),
    PRIMARY KEY (`id_usuario`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
